name: shopapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  carousel_slider: ^5.1.2
  smooth_page_indicator: ^1.2.0
  dio: ^5.9.2
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  google_fonts: ^6.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.jpg
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
